name: Pipeline

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a la rama 'main'

jobs:
  setup:
    runs-on: ubuntu-latest  # Esto se puede cambiar a windows-latest si usas Windows
    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v2
        
      - name: Verificar Python
        run: python --version  # Verificar que Python esté instalado correctamente

      - name: Configurar el entorno de liberación
        run: |
          python -m venv venv  # Crear entorno virtual
          source venv/bin/activate  # Activar el entorno virtual en Linux/Mac
          pip install -r requirements.txt  # Instalar dependencias desde requirements.txt
          
  test:
    runs-on: ubuntu-latest  # Usa el mismo sistema que el job anterior
    needs: setup  # Dependencia del job anterior
    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v2
        
      - name: Ejecutar pruebas
        run: |
          source venv/bin/activate  # Activar el entorno virtual
          pytest tests/ --junitxml=report.xml  # Ejecutar pruebas con pytest
          
      - name: Subir artefactos de prueba
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.xml

  deploy:
    runs-on: ubuntu-latest  # Usa el mismo sistema que el job anterior
    needs: test  # Depende de las pruebas exitosas
    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v2
        
      - name: Empaquetar el juego
        run: |
          source venv/bin/activate  # Activar el entorno virtual
          pyinstaller --onefile --distpath dist/ --workpath build/ --specpath . game.py  # Empaquetar el juego
          echo "Juego desplegado en dist/"
        
      - name: Subir artefactos de despliegue
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
